/*
API Аутентификации

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiAuth

import (
	"encoding/json"
)

// AuthSwitchUserResponse struct for AuthSwitchUserResponse
type AuthSwitchUserResponse struct {
	Token *string `json:"token,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewAuthSwitchUserResponse instantiates a new AuthSwitchUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthSwitchUserResponse() *AuthSwitchUserResponse {
	this := AuthSwitchUserResponse{}
	return &this
}

// NewAuthSwitchUserResponseWithDefaults instantiates a new AuthSwitchUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthSwitchUserResponseWithDefaults() *AuthSwitchUserResponse {
	this := AuthSwitchUserResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AuthSwitchUserResponse) GetToken() string {
	if o == nil || isNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthSwitchUserResponse) GetTokenOk() (*string, bool) {
	if o == nil || isNil(o.Token) {
    return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AuthSwitchUserResponse) HasToken() bool {
	if o != nil && !isNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AuthSwitchUserResponse) SetToken(v string) {
	o.Token = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AuthSwitchUserResponse) GetError() string {
	if o == nil || isNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthSwitchUserResponse) GetErrorOk() (*string, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AuthSwitchUserResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *AuthSwitchUserResponse) SetError(v string) {
	o.Error = &v
}

func (o AuthSwitchUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableAuthSwitchUserResponse struct {
	value *AuthSwitchUserResponse
	isSet bool
}

func (v NullableAuthSwitchUserResponse) Get() *AuthSwitchUserResponse {
	return v.value
}

func (v *NullableAuthSwitchUserResponse) Set(val *AuthSwitchUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthSwitchUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthSwitchUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthSwitchUserResponse(val *AuthSwitchUserResponse) *NullableAuthSwitchUserResponse {
	return &NullableAuthSwitchUserResponse{value: val, isSet: true}
}

func (v NullableAuthSwitchUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthSwitchUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


