/*
API Аутентификации

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiAuth

import (
	"encoding/json"
)

// KeyGetKeyResponse struct for KeyGetKeyResponse
type KeyGetKeyResponse struct {
	Key *string `json:"key,omitempty"`
}

// NewKeyGetKeyResponse instantiates a new KeyGetKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyGetKeyResponse() *KeyGetKeyResponse {
	this := KeyGetKeyResponse{}
	return &this
}

// NewKeyGetKeyResponseWithDefaults instantiates a new KeyGetKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyGetKeyResponseWithDefaults() *KeyGetKeyResponse {
	this := KeyGetKeyResponse{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *KeyGetKeyResponse) GetKey() string {
	if o == nil || isNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyGetKeyResponse) GetKeyOk() (*string, bool) {
	if o == nil || isNil(o.Key) {
    return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *KeyGetKeyResponse) HasKey() bool {
	if o != nil && !isNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *KeyGetKeyResponse) SetKey(v string) {
	o.Key = &v
}

func (o KeyGetKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullableKeyGetKeyResponse struct {
	value *KeyGetKeyResponse
	isSet bool
}

func (v NullableKeyGetKeyResponse) Get() *KeyGetKeyResponse {
	return v.value
}

func (v *NullableKeyGetKeyResponse) Set(val *KeyGetKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyGetKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyGetKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyGetKeyResponse(val *KeyGetKeyResponse) *NullableKeyGetKeyResponse {
	return &NullableKeyGetKeyResponse{value: val, isSet: true}
}

func (v NullableKeyGetKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyGetKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


